# This is the basic workflow to help you get started with Github Actions
name: A Basic Workflow

#Controls when the workflow will run
on:
    # Triggers the workflow for push and pull request events but only for main branch
    push:
        branches: [ "main" ]

    pull_request:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or parallel
jobs: 
    # This workflow contains a single job called 'build'
    build: 
        # The type of runner the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executes as part of the job
        steps:
            # Checksout the repository  under $GITHUB_WORKSPACE, so your job can access it
           - uses: actions/checkout@v3
            # Runs a single command
           - name: Run a one-line script
             run: echo Hello, World !!!

           - name: Run a multi-line script
             run: | 
                echo Add other actions to build,
                echo test, and deploy your project

    build-db:
        runs-on: windows-latest
        steps:
          - run: echo "Hello Windows !!!"
                
    build-api-app:
        needs: build
        runs-on: windows-latest
        steps:
          - run: echo "Hello Windows !!!"
        

    packaging:
        needs: [build, build-api-app]
        runs-on: self-hosted runner
        steps:
          - run: echo "Hello MacOS" 

    


