name: 'Default Environment Variables Values'

on:
    push:

jobs:
    mainjob:
        name: "Print the default environment variable"
        runs-on: ubuntu-latest

        steps:
        - name: print-value-of-env-vars
          run: |
            echo "$GITHUB_ACTION"
            echo "$GITHUB_ENV"
            echo "$RUNNER_NAME"
            echo "$GITHUB_REPOSITORY_OWNER"
